### ISSUE TITLE
clazy

### ISSUE THREAD

**Issue by vadi2** [restyled-io/restylers#32]
https://github.com/KDE/clazy

Best practices checker for Qt (C++) with fixits.

**Comment by pbrisbin** [comment]
This looks really cool! But I might need some help implementing it; the docs seem to assume some general tool-chain familiarity that might be a blocker for me. Please let me know if you'd like help implementing this as a Restyler yourself.

**Comment by vadi2** [comment]
Yes sure, what would you like help with?

**Comment by pbrisbin** [comment]
I was more thinking you (or any contributor who knew this tool well) could take the lead, and I would help them :)

https://github.com/restyled-io/restyled.io/wiki/Adding-a-Restyler

**Comment by pbrisbin** [comment]
Reading up on this a big,

> ### Enabling Fixits
>
> [P]ass ... `-export-fixes=somefile.yaml` for `clazy-standalone`. Then run `clang-apply-replacements <folder_with_yaml_files>`, which will modify your code.

So, this will require an extra script to:

1. Run `clazy-standalone -export-fixes=x/...`, then
2. Run `clang-apply-replacements x`

**Comment by pbrisbin** [comment]
I've started on this (will push a PR soon), but can't get it working.

It seems like `clazy-standalone` is actually trying to compile things (or expects it to somehow have been compiled). Our test case fails with:

```
       Error while trying to load a compilation database:
       Could not auto-detect compilation database for file "./clazy-test-1.cpp"
       No compilation database found in /code or any parent directory
       fixed-compilation-database: Error while opening fixed database: No such file or directory
       json-compilation-database: Error while opening JSON database: No such file or directory
       Running without flags.
       /code/clazy-test-1.cpp:1:10: fatal error: 'QString' file not found
       #include <QString>
                ^~~~~~~~~
       1 error generated.
       Error while processing /code/clazy-test-1.cpp.
```

I'm not sure what would be required to get it working.

**Comment by vadi2** [comment]
Hey thanks for taking up work on this. Clazy requires a file called [compile_commands.json](https://cmake.org/cmake/help/v3.5/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html) which are instructions for the compiler on how to compile a certain file. This file can be generated by a bunch of build systems, including cmake if you pass it the `-DCMAKE_EXPORT_COMPILE_COMMANDS` argument.

I'm not familiar with how restylers works (but looking forward to using it with clazy in) - you might need to get the user to provide some configuration to generate the compile commands file?

**Comment by vadi2** [comment]
It's an autogenerated file and it's typically not checked in because the paths to the libraries would be different on every developers machine. 

Here's an example of how I use another clang-based tool to first generate the file and then run the tool when the file is present: https://github.com/Mudlet/Mudlet/blob/development/.github/workflows/clangtidy-diff-analysis.yml#L107-L136

> And do you think this warning is the reason it can't find QString?

Yeah, that would be it.

**Comment by pbrisbin** [comment]
OK, I think I'm in a good place. The following seems to _function_, without error:

```sh
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
clazy-standalone --export-fixes="$tmp"/fixes.yaml --checks=level0 <input>
clang-apply-replacements "$tmp"
```

The problem now is that it seems to do nothing. `fixes.yaml` is not produced, apply-replacements is a no-op, and my test fails because `.mid` was not replaced by `midRef`.

:thinking:
