### ISSUE TITLE
Bad Restylers manifest - Unknown executable: "lua"

### ISSUE THREAD

**Issue by stackptr** [restyled-io/restylers#509]
Been seeing the Restyled action fail in [freckle/megarepo][megarepo] recently. This is the entire log of a recent run:

```
{"time":"2023-06-08T22:27:05.867318078Z","level":"info","location":{"package":"restyler-0.2.0.0-K1H5qEM2SmXKTdBKC6Ip2e","module":"Restyler.Setup","file":"src/Restyler/Setup.hs","line":56,"char":5},"message":{"text":"Restyler started","meta":{"owner":"freckle","repo":"megarepo","pull":27723}}}
{"time":"2023-06-08T22:27:06.210184458Z","level":"info","location":{"package":"restyler-0.2.0.0-K1H5qEM2SmXKTdBKC6Ip2e","module":"Restyler.Setup","file":"src/Restyler/Setup.hs","line":89,"char":5},"message":{"text":"Cloning repository"}}
Switched to branch 'pull-27723'
{"time":"2023-06-08T22:27:40.193210578Z","level":"info","location":{"package":"restyler-0.2.0.0-K1H5qEM2SmXKTdBKC6Ip2e","module":"Restyler.RemoteFile","file":"src/Restyler/RemoteFile.hs","line":29,"char":5},"message":{"text":"Fetching remote file","meta":{"path":"/tmp/restylers-dev.yaml"}}}
{"time":"2023-06-08T22:27:43.381995114Z","level":"error","location":{"package":"restyler-0.2.0.0-K1H5qEM2SmXKTdBKC6Ip2e","module":"Restyler.Exit","file":"src/Restyler/Exit.hs","line":72,"char":9},"message":{"text":"Exception:\nError loading restylers.yaml definition:\nAesonException \"Error in $[19].interpreters[0]: Unknown executable: \\\"lua\\\"\"\n\n===\n\nThis could be caused by an invalid or too-old restylers_version in\nyour configuration. Consider removing or updating it.\n\nIf that's not the case, this is a bug in our system that we are\nhopefully already working to fix.\n\n- https://github.com/restyled-io/restyled.io/wiki/Restyler-Versions\n- https://github.com/restyled-io/restyled.io/wiki/Common-Errors:-.restyled.yaml\n","meta":{"error":{"description":"bad Restylers manifest","exitCode":12,"severity":"error","tag":"invalid-restylers-yaml"}}}}
{"time":"2023-06-08T22:27:44.21583806Z","level":"info","location":{"package":"main","module":"Main","file":"app/main.hs","line":29,"char":11},"message":{"text":"Restyler done","meta":{"exitCode":12}}}
```

The `.restyled.yaml` in megarepo has not been touched in a few weeks and there is no mention of Lua in it. However, I see the most recent commit 3cab672 in this repo is related to Lua, so maybe that is the cause? The links in the error do not seem relevant.

[megarepo]: https://github.com/freckle/megarepo

**Comment by pbrisbin** [comment]
Ah, I know what I broke but I won't be able to fix it till tomorrow. Good news is this should just be the dev channel. Please switch to stable for now.

On Thu, Jun 8, 2023, at 8:19 PM, ✿ corey wrote:
> 
> 
> Been seeing the Restyled action fail in freckle/megarepo <https://github.com/freckle/megarepo> recently. This is the entire log of a recent run:
> 
> `{"time":"2023-06-08T22:27:05.867318078Z","level":"info","location":{"package":"restyler-0.2.0.0-K1H5qEM2SmXKTdBKC6Ip2e","module":"Restyler.Setup","file":"src/Restyler/Setup.hs","line":56,"char":5},"message":{"text":"Restyler started","meta":{"owner":"freckle","repo":"megarepo","pull":27723}}}
> {"time":"2023-06-08T22:27:06.210184458Z","level":"info","location":{"package":"restyler-0.2.0.0-K1H5qEM2SmXKTdBKC6Ip2e","module":"Restyler.Setup","file":"src/Restyler/Setup.hs","line":89,"char":5},"message":{"text":"Cloning repository"}}
> Switched to branch 'pull-27723'
> {"time":"2023-06-08T22:27:40.193210578Z","level":"info","location":{"package":"restyler-0.2.0.0-K1H5qEM2SmXKTdBKC6Ip2e","module":"Restyler.RemoteFile","file":"src/Restyler/RemoteFile.hs","line":29,"char":5},"message":{"text":"Fetching remote file","meta":{"path":"/tmp/restylers-dev.yaml"}}}
> {"time":"2023-06-08T22:27:43.381995114Z","level":"error","location":{"package":"restyler-0.2.0.0-K1H5qEM2SmXKTdBKC6Ip2e","module":"Restyler.Exit","file":"src/Restyler/Exit.hs","line":72,"char":9},"message":{"text":"Exception:\nError loading restylers.yaml definition:\nAesonException \"Error in $[19].interpreters[0]: Unknown executable: \\\"lua\\\"\"\n\n===\n\nThis could be caused by an invalid or too-old restylers_version in\nyour configuration. Consider removing or updating it.\n\nIf that's not the case, this is a bug in our system that we are\nhopefully already working to fix.\n\n- https://github.com/restyled-io/restyled.io/wiki/Restyler-Versions\n- https://github.com/restyled-io/restyled.io/wiki/Common-Errors:-.restyled.yaml\n","meta":{"error":{"description":"bad Restylers manifest","exitCode":12,"severity":"error","tag":"invalid-restylers-yaml"}}}}
> {"time":"2023-06-08T22:27:44.21583806Z","level":"info","location":{"package":"main","module":"Main","file":"app/main.hs","line":29,"char":11},"message":{"text":"Restyler done","meta":{"exitCode":12}}}
`

**Comment by pbrisbin** [comment]
This was fixed in https://github.com/restyled-io/restyler/commit/f1127842e19f1ed7cc5c073dce70f624ef8d8185
