### ISSUE TITLE
prettier-json

### ISSUE THREAD

**Issue by DanielHabenicht** [restyled-io/restylers#56]
https://prettier.io/

**Comment by DanielHabenicht** [comment]
Is this possible with one of the current prettier plugins? (e.g. by extending the `include` section)
Or do I have to create a new restyler?

**Comment by pbrisbin** [comment]
Always happy to revisit the decision, but I decided originally that even if it was the same actual image and tool (e.g. prettier) but was a meaningfully different "format", I would define a separate Restyler for it. However, I made it easy to do that in the case where it is just the same thing under a different name (and different options, include, etc) -- I call this process "overrides".

In such a case, you'll only need to define `info.yml`. You can see examples of this with [`prettier-yaml`](https://github.com/restyled-io/restylers/blob/master/prettier-yaml/info.yaml) and [`prettier-markdown`](https://github.com/restyled-io/restylers/blob/master/prettier-markdown/info.yaml).

If you need to install plugins or other tools, you'll need a separate `Dockerfile`, which at that point makes it a completely separate Restyler. [`prettier-ruby`](https://github.com/restyled-io/restylers/tree/master/prettier-ruby) is an example of this.

I'm not familiar with Prettier, or its JSON functionality, so I don't know which this would be.

To be clear, I'm 100% on board with adding `prettier-json`, but I do want to mention two workarounds:

- You could configure `prettier` to include `**/*.json` files locally in your `.restyled.yaml`
- You could use our `jq` Restyler
