### ISSUE TITLE
terraform 0.12

### ISSUE THREAD

**Issue by bryantbiggs** [restyled-io/restylers#74]
~~I would have opened a PR but it doesn't look like that is supported.~~

The vast majority of the Terraform community has upgraded and moved on to 0.12.x, could we upgrade to the latest version of [0.12.24](https://github.com/hashicorp/terraform/releases)? There are significant improvements in 0.12 (better type system) and this will be a breaking change

**Comment by pbrisbin** [comment]
> I would have opened a PR but it doesn't look like that is supported.

What do you mean? PRs in this repository are very much encouraged.

**Comment by bryantbiggs** [comment]
oh forgive me, not sure what I was thinking - long day! give me a minute

**Comment by pbrisbin** [comment]
No worries at all! Thanks for contributing, no worries if you can't get tests to run or anything, happy to help out once the PR's open.
