### ISSUE TITLE
Don't reformat .patch files.

### ISSUE THREAD

**Issue by iphydf** [restyled-io/restylers#77]
These are whitespace sensitive and require that e.g. trailing whitespace is exactly the way it is in the to-be-patched source file. The "whitespace" restyler (I think) modifies them. No restyler should ever touch .patch files.

**Comment by pbrisbin** [comment]
> No restyler should ever touch .patch files

If that's the case (I tend to agree), we could fix it by adding to the global [`exclude`](https://github.com/restyled-io/restyler/blob/master/config/default.yaml#L5)s.
