### ISSUE TITLE
pydocstyle

### ISSUE THREAD

**Issue by leotrs** [restyled-io/restylers#88]
http://www.pydocstyle.org/en/stable/usage.html

**Comment by pbrisbin** [comment]
Does this too auto-fix anything? It looks to me like a linter/checker, but I could me missing something.

Restyled operates by automatically fixing style problems and opening a PR with those fixes. Tools that don't actually auto-fix can't be used as Restylers.

**Comment by leotrs** [comment]
Argh you're right!
